### ISSUE TITLE
branch point sometimes does not emit any S-walls

### ISSUE THREAD

**Issue by neitzke** [chan-y-park/loom#19]
Using the config file "config/issue_2.ini" with current master, if I leave all parameters at their default values, everything looks great! But, if I change the parameter "z_r" in "differential_parameters" to 1, then there seems to be a problem: no error is raised but the output is wrong -- one of the branch points (the one at lower right) does not emit any S-walls.

**Comment by plonghi** [comment]
The failure is due to get_s_wall_seeds, for that branch point it returns no seeds at all.
There is a parameter which controls which seeds to keep, it's delta and it's controlled by accuracy in the config file. 
Setting accuracy to 1e-05 solves the problem with seeds, they all get generated.
However, with this accuracy, CGAL gives a segmentation fault error.

**Comment by plonghi** [comment]
Solved by setting accuracy to 1e-05. The errors with CGAL don't appear anymore after the overhaul of trivialization and seeding

![issue_2_resolved](https://cloud.githubusercontent.com/assets/8493120/10491249/ef016cc6-72a5-11e5-801e-ca09d3bc7aa6.png)
