### ISSUE TITLE
Data saving doesn't work anymore

### ISSUE THREAD

**Issue by plonghi** [chan-y-park/loom#30]
With the new version on master branch I get the following funny error when trying to save data

Make a directory /home/longhi/results/loom/test_all_config_2015-10-27-06.08/AD_SO_4_data/ to save data.
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Traceback (most recent call last):
  File "loom/run_single_phase.py", line 29, in <module>
    loom.save(c, d, data_dir=saving_folder_path+filename+'_data/')
  File "/home/longhi/loom/loom/api.py", line 199, in save_spectral_network
    version = get_current_branch_version() 
  File "/home/longhi/loom/loom/api.py", line 350, in get_current_branch_version
    ['git', 'rev-parse', 'HEAD']
  File "/usr/local/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128

**Comment by chan-y-park** [comment]
It failed when checking the current version of the git branch because `loom` was not run in its directory. Probably you used the test script? I will look into the problem and see if there is a better way to have a version checking. Of course we can just make it work by disabling the version checking, but let's see if we can have an easy fix of it.

**Comment by plonghi** [comment]
yes I was working outside the directory, as I always did, but previously it was working

why is loom now checking the git version?

**Comment by chan-y-park** [comment]
It's not really a major thing, I was trying to save the git branch version into the data file so that we can see when we saved it using which branch. That way we can use the data file even if we changed the code by going back to the previous version of the branch.

**Comment by chan-y-park** [comment]
OK, I disabled the version checking in the master branch as a temporary measure, so it should work now. I will try to do a genuine fix soon. By the way, if you are running `loom` outside the default directory (where `default.ini` and `gmain.py` are in), how did you manage to overcome the following difficulty? If I run `loom` without changing the working directory to the default directory, I get

```
IOError: [Errno 2] No such file or directory: '/home/chan/logs/loom.log'
```

which occurs because there is no `logs` directory where the command runs. If we run it in the default directory it does not happen because `logs` directory is part of the git repo.

**Comment by plonghi** [comment]
Thanks for the fix, I overcame that by just creating a logs directory in the folder where I usually run the code from.

Question: is the logging of the git version just an info, or is it used to load data every time?

**Comment by chan-y-park** [comment]
I see, probably I need to fix that too. Now I realize that actually there may be more bugs hidden because I always assumed that `loom` will run in the default directory.

The plan is we will save the version every time and check the version every time when we load data, but it will just give a warning even if the version doesn't match, because it can surely happen that versions are different but still data can be understood by `loom`.

**Comment by plonghi** [comment]
Indeed, I think that the warning may be just an annoyance in most cases. But it's a good idea to store that data, whenever available (and it's not a big deal if sometimes it's not available, e.g. because we run from outside the directory)

I tried running the various files in the config folde, with phase 0.1, the following ones failed:
pure so(4)
pure su(2)
seeding type I
did you change the config files? or could it be something deeper?

**Comment by chan-y-park** [comment]
I hope I didn't, but there was a good amount of mixup when I tried to merge branches, so maybe something went wrong while merging. I will look into it.

**Comment by plonghi** [comment]
Here's one error message, regarding so(4)

Traceback (most recent call last):
  File "loom/run_single_phase.py", line 29, in <module>
    loom.save(c, d, data_dir=saving_folder_path+filename+'_data/')
  File "/home/longhi/loom/loom/api.py", line 211, in save_spectral_network
    json_data = sw_data.get_json_data()
  File "/home/longhi/loom/loom/trivialization.py", line 279, in get_json_data
    json_data = super(SWDataWithTrivialization, self).get_json_data()
  File "/home/longhi/loom/loom/geometry.py", line 534, in get_json_data
    'punctures': [p.get_json_data() for p in self.punctures],
  File "/home/longhi/loom/loom/geometry.py", line 334, in get_json_data
    json_data['Ciz'] = ctor2(self.Ciz)
  File "/home/longhi/loom/loom/misc.py", line 39, in ctor2
    return (complex_number.real, complex_number.imag)
AttributeError: 'Zero' object has no attribute 'real'

**Comment by chan-y-park** [comment]
Good, that was another bug I made. I fixed it and it should work now. By the way, do you think the warning message about the version is not necessary?

And let me recommend you using GUI, it's kinda nicer now. :)

**Comment by chan-y-park** [comment]
Oops, wrong test, still not working. I will fix it soon.

**Comment by plonghi** [comment]
thanks for fixing this promptly, please have a look at the 'seeding type I' run if you have a chance, the error was different, and I'm not sure if it has something to do with the new changes, but I didn't have it before, perhaps a fix I introduced got lost or something like that?

I think the warning is probably unnecessary, because it would pop up all the time and for no good reason most times. But I agree that storing the git data is good practice

**Comment by chan-y-park** [comment]
pure_SO_4 and pure_SU_2 working, now testing seeding_type_I.

The reason that I thought that printing the warning maybe a good idea is that otherwise we may have no hint what is wrong when we loaded data files of incorrect versions. Without a warning message it may just fail in the middle, leaving us puzzled. But I also see your point, so let's think about it.

By the way, seeding_type_I test just finished, and actually it's kind of a major one, in the sense that it is not related to any change in the API but rather it stumbled upon a branch point that cannot be classified by a root. Previously it raised no error when finding such a branch point but I changed it to raise NotImplementedError (thinking that we should stop running `loom` if we find such a branch point) and that's why it fails. Why do we have such a branch point in the config file?

**Comment by plonghi** [comment]
Accidental branch points will arise generally in D-type covers (that's one of the remarks that Donagi makes about Hitchin's work)

Before the code was dealing with them, by just recognizing these, logging their presence, and then ignoring them.
The reason why the code gets stuck now is that it seems you changed the logging.info commend with a raise NotimplementedError. If you switchi it back it should probably work again?

**Comment by chan-y-park** [comment]
Yes it should go over that part if we remove that, but I feel a bit worried about its existence. Are we saying then we have an accidental singularity (in the sense of a singular algebraic curve) for such a case? How do we know that there should be no S-wall coming out of that point?

**Comment by chan-y-park** [comment]
For the curve

```
x^{6} - 3 x^{4} + 3 x^{2} + z - 1 = 0
```

the problem happens at `z = 1`, where the local curve looks like

```
\delta z + 3 (\delta x)^2 =0, \delta z = z - 1, \delta x = x - 0,
```

and now I see that we explicitly declared there will be no S-walls because the two sheets correspond to the zero weights, and it is not an accidental singularity, so it seems fine. I will remove the raising of the exception.

Actually I was worrying about a totally different situation, where we do have an accidental singularity, which will also not be classified by a root because it is not a branch point and has no monodromy around it. And there is a chance that we may meet such a case, which will require an extra consideration to study because so far we've been excluding such a scenario altogether.

By the way, what is the physics behind the curve above? I can't identify the Seiberg-Witten curve with what I know...

**Comment by plonghi** [comment]
At that point, it happens that <\varphi, v> = 0 for some weight v.
But the 'weyl branching property' tells us that ramification should occur only when <\varphi, \alpha>=0 for some root. In D-type the two are generally distinct cases.
Sticking to the definition of S-walls that we give (motivated by nonabelianization), there should be no S-wall.

Regarding the specific curve, it's not from any theory, it's just a prototype that is compatible with general constraints on D-type spectral curves

--- I saw your comment just now, indeed your observation is correct

**Comment by plonghi** [comment]
By the way, what is the precise idea you have in mind for an "accidental singularity", as opposed to these kind of non-root-type zeros of the discriminant (which we already handle)?

**Comment by chan-y-park** [comment]
It's what is described in Section 4 of Donagi's paper, or in page 9 of Martinec-Warner.

**Comment by plonghi** [comment]
Well, you see, this is precisely one of those points and we handle it. 
So I'm really asking: what other cases are you worried about? Any particular ideas in mind?

**Comment by chan-y-park** [comment]
What I had in mind was something like `x^2 = z^2` for `A_1`-type, the one Andy pointed out previously.

**Comment by chan-y-park** [comment]
And now `seeding_type_I.ini` should work. Still no version saving/checking, though.

**Comment by plonghi** [comment]
That's not a good example, because it appears at non-generic points on the Coulomb branch. 
The 'accidental singularities' of Donagi are stable. 

In fact, it can't be one of Donagi's singularities also because there are no such things in A_1 type for the fundamental rep

**Comment by chan-y-park** [comment]
Maybe I was wrong to say it's the accidental singularity that Donagi mentioned; but I still worry about such a case. They indeed happen at a non-generic point of the Coulomb branch for a minuscule rep spectral cover, but they will happen at a generic point of the Coulomb branch for a general rep spectral cover. 

Oh, by the way, when I say I worry about it, I didn't mean that we should worry about it now. As long as we don't have to study such a non-generic curve, we don't have to worry about it now. I just wanted to make `loom` print a warning message if we hit such a non-generic situation.

**Comment by chan-y-park** [comment]
Version saving reintroduced in the `master` branch, hope this time it works without a problem...

**Comment by chan-y-park** [comment]
So far it works without a major problem. Closing this issue.
