### ISSUE TITLE
Problem @ check_cuts()

### ISSUE THREAD

**Issue by chan-y-park** [chan-y-park/loom#8]
Start with the default configuration in `include_trivialization` branch point, checksum `23d1797`, set phase to `2.3575`, then it fails with the following error message:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
    return self.func(*args)
  File "/home/chan/loom/loom/gui.py", line 283, in button_generate_action
    phase=eval(self.entry_phase.get()),
  File "/home/chan/loom/loom/api.py", line 79, in generate_spectral_network
    spectral_network.grow(config, sw)
  File "/home/chan/loom/loom/spectral_network.py", line 85, in grow
    self.check_cuts(self.s_walls[i], sw_data)
  File "/home/chan/loom/loom/spectral_network.py", line 487, in check_cuts
    g = interpolate.splrep(traj_t, traj_x - x_0, s=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy/interpolate/fitpack.py", line 465, in splrep
    raise TypeError('m > k must hold')
TypeError: m > k must hold
```

It started to occur after merging Andy's mass-limit update, i.e. it worked at `cc99ad5` but it failed at `b09774a`, possibly be related to the introduction of mass parameters in `SWall` and its interference with `SpectralNetwork.check_cuts()`

**Comment by neitzke** [comment]
Sorry, probably my fault, I'll check it out.

**Comment by neitzke** [comment]
OK, I understand: with mass_limit turned on, you can get walls which are extremely short -- only 1 entry in the data array (because they are born at a mass which exceeds mass_limit, so they don't propagate at all.) interpolate.splrep wants at least 3 entries since it is doing cubic interpolation. This could be fixed either by deleting those short walls or by including a check that there are at least 3 entries, or by doing both. Morally I feel that one should probably do both, since even if you kill walls that have only 1 entry, there is still some possible edge case where you get exactly 2 entries.

**Comment by neitzke** [comment]
OK, I got rid of the non-propagating walls (7cbb6153243a3), which should fix the issue 99.9% of the time, but I'll leave this open because morally speaking, check_cuts() should also be changed.

**Comment by chan-y-park** [comment]
Thank you very much, Andy! I was planning to look at the issue more closely but you already figured it out. 

Probably we need to explore various possibilities of how to implement a branch cut, including the implementation of check_cuts(). What I mean is whether we want branch cuts to be vertical, to be of a certain phase, to be radial projections from a fixed point, or even to be customizable by a user.

**Comment by plonghi** [comment]
Changed check_cuts() to determine_root_type(), and implemented the check that a wall be at least of length 3. Closing thread.
